---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-api
  labels:
    app: log
    component: api
spec:
  selector:
    matchLabels:
      app: log
      component: api
  template:
    metadata:
      labels:
        app: log
        component: api
    spec:
      containers:
        - image: dontan001/xuanwu-log:latest
          imagePullPolicy: Always
          name: api
          resources:
            requests:
              memory: "128Mi"
              cpu: "1"
            limits:
              memory: "128Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: log-api
spec:
  selector:
    app: log
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080