---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup
  namespace: xuanwu-log
data:
  config.yaml: |
    data:
      loki:
        address: http://loki-loki-distributed-querier.loki:3100
    queries:
    - query: "{job=\"fluent-bit\",app=\"yinglong\"}"
      schedule:
        interval: 3
        max: 8
    archive:
      type: zip
      workingDir: /var/log/xuanwu-log
      namePattern: "%s.log"
      s3:
        bucket: donggetest
        region: us-west-2