---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: xuanwu-log
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: xuanwu-log-schedule
            imagePullPolicy: Always
            args:
            - -config.file=/etc/config/config.yaml
            env:
            - name: ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: backup
                  key: AccessKeyID
                  optional: true
            - name: ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: backup
                  key: AccessKey
                  optional: true
            volumeMounts:
            - name: config
              mountPath: /etc/config
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap:
              name: backup
              defaultMode: 420