---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: dontan001/xuanwu-log:schedule
            imagePullPolicy: Always
            args:
              - -config.file=/etc/config/config.yaml
            volumeMounts:
            - name: config
              mountPath: /etc/config
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap:
              name: backup
              defaultMode: 420