---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api
data:
  config.yaml: |
    server:
      http_listen_port: 8080
      working_directory: /var/log/log-api
    data:
      loki:
        address: http://loki-loki-distributed-querier:3100