---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  namespace: xuanwu-log
data:
  config.yaml: |
    server:
      port: ":8080"
      workingDir: /var/log/xuanwu-log
    data:
      loki:
        address: http://loki-loki-distributed-querier.loki:3100