---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: xuanwu-log
  labels:
    app: log
    component: api
spec:
  selector:
    matchLabels:
      app: log
      component: api
  template:
    metadata:
      labels:
        app: log
        component: api
    spec:
      containers:
        - image: dontan001/xuanwu-log:api
          imagePullPolicy: Always
          name: api
          resources:
            requests:
              memory: "128Mi"
              cpu: "1"
            limits:
              memory: "128Mi"
              cpu: "1"
          args:
          - -config.file=/etc/config/config.yaml
          - -config.backup=/etc/backup/config.yaml
          volumeMounts:
          - name: config
            mountPath: /etc/config
          - name: configBackup
            mountPath: /etc/backup
      volumes:
      - name: config
        configMap:
          name: api
          defaultMode: 420
      - name: configBackup
        configMap:
          name: backup
          defaultMode: 420