---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: log
    component: api
spec:
  selector:
    matchLabels:
      app: log
      component: api
  template:
    metadata:
      labels:
        app: log
        component: api
    spec:
      containers:
        - image: dontan001/xuanwu-log:api
          imagePullPolicy: Always
          name: api
          resources:
            requests:
              memory: "128Mi"
              cpu: "1"
            limits:
              memory: "128Mi"
              cpu: "1"