---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: xuanwu-log
spec:
  selector:
    app: log
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080