apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xuanwu-log.fullname" . }}-api-config
  labels:
  {{- include "xuanwu-log.labels" . | nindent 4 }}
data:
  config.yaml: |
    data:
      loki:
        address: {{ .Values.apiConfig.configYaml.data.loki.address | quote }}
    server:
      port: {{ .Values.apiConfig.configYaml.server.port | quote }}
      workingDir: {{ .Values.apiConfig.configYaml.server.workingDir | quote }}