apiVersion: v1
kind: Service
metadata:
  name: {{ include "xuanwu-log.fullname" . }}-api-service
  labels:
  {{- include "xuanwu-log.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  selector:
    app: log
    component: api
  {{- include "xuanwu-log.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.apiService.ports | toYaml | nindent 2 -}}