apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xuanwu-log.fullname" . }}-backup-secret
  labels:
  {{- include "xuanwu-log.labels" . | nindent 4 }}
data:
  AccessKey: {{ required "backupSecret.accessKey is required" .Values.backupSecret.accessKey
    | b64enc | quote }}
  AccessKeyID: {{ required "backupSecret.accessKeyID is required" .Values.backupSecret.accessKeyID
    | b64enc | quote }}
type: Opaque