apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xuanwu-log.fullname" . }}-api
  labels:
    app: log
    component: api
  {{- include "xuanwu-log.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: log
      component: api
    {{- include "xuanwu-log.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: log
        component: api
      {{- include "xuanwu-log.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -config.file=/etc/config/config.yaml
        - -config.backup=/etc/backup/config.yaml
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.api.api.image.repository }}:{{ .Values.api.api.image.tag | default
          .Chart.AppVersion }}
        imagePullPolicy: Always
        name: api
        resources: {{- toYaml .Values.api.api.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/config
          name: config
        - mountPath: /etc/backup
          name: configbackup
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ include "xuanwu-log.fullname" . }}-api-config
        name: config
      - configMap:
          defaultMode: 420
          name: {{ include "xuanwu-log.fullname" . }}-backup-config
        name: configbackup